name: Azure Deploy

on:
  push:
permissions:
      id-token: write
      contents: read   

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'  

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dtdc'
        resource-group-name: dev
        slot-name: 'production'  
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ github.workspace }}/target/*.jar'
