name: Bh-javaapp-backend

on:
  workflow_dispatch:
env:
  PRODUCT_VERSION: "latest"
  SSL_CERT_DIR: "/etc/pki/tls/certs"
  NODE_EXTRA_CA_CERTS: /etc/pki/ca-trust/source/anchors/ca.crt
  AZURE_WEBAPP_NAME: futurabackend-webapp-dev
  AZURE_WEBAPP_PACKAGE_PATH: bh-app-apis
  JAVA_VERSION: '17'

permissions:
  id-token: write
  contents: read  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.2.1

      - name: Build with Maven
        run: mvn clean install
        working-directory: '${{ github.workspace }}/bh-app-apis'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/bh-app-apis/target.jar'

  deploy:
    runs-on:  ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'dev'
      url: ${{ needs.build-and-deploy.outputs.webapp-url }}

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          package: '*.jar'