name: dev

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
          java-version: '17'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: '${{ github.workspace }}/demo'
      
    - name: Azure Login
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v1
      with:
        resource-group-name: dev
        app-name: backednjava
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: /home/runner/work/qa/qa/demo/target/demo-0.0.1-SNAPSHOT.jar
