name: Bh-javaapp-backend-fuctoionapp

on:
  workflow_dispatch:
env:

  AZURE_WEBAPP_NAME: dev-test12
  AZURE_WEBAPP_PACKAGE_PATH: azure functions
  JAVA_VERSION: '17'

permissions:
  id-token: write
  contents: read  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.2.1

      - name: Build with Maven
        run: mvn clean package
        working-directory: '${{ github.workspace }}/azure functions'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/azure functions/target.jar'

  deploy:
    runs-on:  ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'dev'
      url: ${{ needs.build-and-deploy.outputs.webapp-url }}

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'dev-test12'
          slot-name: 'production'
          package: '*.jar'
        