name: futura-dev

on:
  push:
    

env:
  AZURE_WEBAPP_NAME: backendjava 
  AZURE_WEBAPP_PACKAGE_PATH: helloazure
  JAVA_VERSION: '17'

permissions:
  id-token: write
  contents: read  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.2.1


      - name: Verify JAR file
        run: ls -R helloazure/target/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: helloazure-0.0.1-SNAPSHOT.jar
          path: 'helloazure/target/helloazure-0.0.1-SNAPSHOT.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'dev'
      url: ${{ needs.build-and-deploy.outputs.webapp-url }}

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: helloazure-0.0.1-SNAPSHOT.jar

      

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v1
        with:
          app-name: backednjava
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'helloazure-0.0.1-SNAPSHOT.jar'
