name: Azure Function App - myappfunctions

on:
  push:

env:
  AZURE_FUNCTIONAPP_NAME: dev-test12 # set this to your function app name on Azure
  JAR_FILE_PATH: '${{ github.workspace }}/azure functions/target/azure-1.0-SNAPSHOT.jar' # specify the path to your JAR file
  JAVA_VERSION: '17' # set this to the java version to use

permissions:
  id-token: write
  contents: read   

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      # No Maven build step is needed as we are using a pre-built JAR file

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Deploy JAR to Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group dev \
            --name dev-test12 \
            --src azure functions/target/azure-1.0-SNAPSHOT.jar