# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Java project to Azure Function App - dev-test12

on:
  push:


env:
  AZURE_FUNCTIONAPP_NAME: dev-test12 # set this to your function app name on Azure
  PACKAGE_DIRECTORY: 'azure functions/target/azure-1.0-SNAPSHOT.jar' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use

permissions:
  id-token: write
  contents: read   

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Restore Project Dependencies Using Mvn'
        shell: pwsh
        run: |
          pushd './${{ env.PACKAGE_DIRECTORY }}'
          popd
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'dev-test12'
          slot-name: 'production'
          package: '${{ env.PACKAGE_DIRECTORY }}'
          respect-pom-xml: true
          