name:   App - dev-test

on:
  push:
   

env:
  
  AZURE_FUNCTIONAPP_NAME: 'dev-app123' 
  PACKAGE_DIRECTORY: 'azure functions' 
  JAVA_VERSION: '17' 
permissions:
  id-token: write
  contents: read  

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.2.1    

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/azure functions/target/azure-1.0-SNAPSHOT.jar'
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'dev-app123'
          slot-name: 'production'
          package: 'azure functions'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          respect-pom-xml: true
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TAG_GITHUB_TOKEN }} 
        with:
          #tag_name: ${{ github.run_number }}
          #release_name: Release ${{ github.run_number }}     
          tag_name: v2.0.0.2
          release_name: Release v2.0.0.2