name: Deploy Azure Function App

on:
  push:
    
permissions:
  id-token: write
  contents: read  

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest

      - name: Deploy to Azure Function App
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload JAR file to Azure Function App
        run: az functionapp deployment source config-zip --resource-group dev --name dtdc-call-dev --src azure-functions/target/azure-1.0-SNAPSHOT.jar
