name: Deploy Java project to Azure webapp

on:
  push:

env:
  AZURE_WEBAPP_NAME: backendjava
  # set this to your function app name on Azure
  PACKAGE_DIRECTORY: 'helloazure' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: 'helloazure'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'   
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: helloazure/target/*.jar
