name: Bh-javaapp-backend

on:
  push:

env:

  AZURE_WEBAPP_NAME: java-projectdev
  # set this to your function app name on Azure
  PACKAGE_DIRECTORY: 'bh-dev-rest 2' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use
  
permissions:
  id-token: write
  contents: read  

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment:
      name: dev

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          maven-version: '3.8.2'

      - name: Build and install with Maven
        run: |
          mvn install
          # Additional debugging command if needed
          mvn help:effective-settings

        working-directory: bh-app-apis

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/bh-app-apis/target/*.jar'

  deploy:
    runs-on: self-hosted
    needs: build-and-deploy
    environment:
      name: 'dev'
      url: ${{ needs.build-and-deploy.outputs.webapp-url }}

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '${{ github.workspace }}/java-app/*.jar'
