name: Azure-Angular frontend

on:
  push:

env:
  AZURE_WEBAPP_NAME: 'angular-app-bh'
  AZURE_WEBAPP_PACKAGE_PATH: 'bh-dev-frondend/dist/bh-dev-frondend'
  NODE_VERSION: '16'  

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
       
      - name: Change working directory
        run: cd ${{ github.workspace }}

      - name: npm install, build, and test
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' 

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: bh-dev-frondend

      - name: Unzip artifact for deployment
        run: unzip -o release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
