name: Deploy Java project to Azure webapp

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: java-projectdev
  # set this to your function app name on Azure
  PACKAGE_DIRECTORY: 'bh-dev-rest 2' # set this to the directory which contains pom.xml file
  JAVA_VERSION: '17' # set this to the java version to use

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: 'bh-dev-rest 2'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}' 
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: java-projectdev
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'bh-dev-rest 2/.mvn/wrapper/*.jar'
