name: deployment webapp jar file

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read   

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: '${{ github.workspace }}/demo'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/demo/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build-and-deploy
    environment:
      name: 'dev'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'demolab-1'
          resource-group-name: dev
          slot-name: 'Production'
          package: '*.jar'
          
      - name: Use Azure PowerShell
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |
            az webapp start --name demolab-1 --resource-group dev
